# Copy to configs/paths.yaml and edit if needed.
# If paths.yaml is missing, scripts should fall back to defaults.

# Location of the unzipped precomputed predictions from Zenodo (test_preds.zip)
preds_dir: "./test_preds"

# Where to write outputs for the "camera-ready-repro" branch
outputs_root: "./outputs"

# (Optional) Where intermediate matrices should go (G, Ga, Gn, Gna, coverage CSVs)
derived_dir: "./outputs/derived"

# (Optional) Figures and tables
figures_dir: "./outputs/figures"
tables_dir: "./outputs/tables"
logs_dir: "./outputs/logs"
